enable-magisk-update = true
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"

[YouTube]
app-name = "YouTube"
build-mode = "both"
included-patches = "'Hide double tap overlay filter' 'Hide player button background' 'MaterialYou'"
excluded-patches = "'Custom branding name YouTube'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
# enabled = false
build-mode = "both"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
included-patches = "'Hide overlay filter' 'Hide player overlay filter' 'Replace cast button'"
excluded-patches = "'Custom branding name YouTube Music'"
