enable-magisk-update = true
patches-version = "v2.226.0-dev.11"
integrations-version = "v0.153.0-dev.5"


[YouTube]
app-name = "YouTube"
build-mode = "both"
included-patches = "'Custom branding icon YouTube' 'Force hide player buttons background' 'Hide Shorts dimming' 'Hide animated button background' 'MaterialYou'"
excluded-patches = "'Custom package name' 'Disable splash animation' 'Enable debug logging'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
# enabled = false
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
included-patches = "'Custom branding icon YouTube Music' 'Hide overlay filter' 'Hide player overlay filter'"
excluded-patches = "'Custom package name' 'Enable debug logging'"
