enable-magisk-update = true
patches-version = "v2.225.0-dev.21"
integrations-version = "v0.152.0-dev.12"

[YouTube]
app-name = "YouTube"
build-mode = "both"
included-patches = "'Custom branding icon YouTube' 'Force disable Shorts dim' 'Force hide animated button background' 'Force hide player buttons background' 'MaterialYou'"
excluded-patches = "'Disable splash animation' 'Enable debug logging'"
version = "19.16.39"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
# enabled = false
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
included-patches = "'Hide overlay filter' 'Hide player overlay filter' 'Replace cast button'"
excluded-patches = "'Custom branding name YouTube Music'"
