enable-magisk-update = true
patches-version = "v2.227.0-dev.17"
integrations-version = "v0.154.0-dev.5"


[YouTube]
build-mode = "both"
included-patches = "'Custom branding icon YouTube' 'Force hide player buttons background' 'Hide Shorts dimming' 'MaterialYou'"
excluded-patches = "'Disable splash animation' 'Enable debug logging'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
# enabled = false
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
included-patches = "'Custom branding icon YouTube Music' 'Hide overlay filter' 'Hide player overlay filter'"
excluded-patches = "'Enable debug logging'"