enable-magisk-update = true
patches-version = "v2.226.0-dev.2"
integrations-version = "v0.153.0-dev.1"


[YouTube]
app-name = "YouTube"
build-mode = "both"
included-patches = "'Custom branding icon YouTube' 'Force hide player buttons background' 'Hide animated button background' 'Hide shorts dimming' 'MaterialYou'"
excluded-patches = "'Custom package name' 'Enable debug logging'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
# enabled = false
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
included-patches = "'Hide overlay filter' 'Hide player overlay filter' 'Replace cast button'"
excluded-patches = "'Custom package name' 'Enable debug logging'"