enable-magisk-update = true
# patches-version = "v2.227.0-dev.23"
# integrations-version = "v0.154.0-dev.8"


[YouTube]
build-mode = "both"
included-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Hide Shorts dimming' 'MaterialYou'"
excluded-patches = "'Alternative thumbnails' 'Bypass image region restrictions' 'Disable splash animation' 'Enable debug logging' 'Force player buttons background'"
version = "19.28.35"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
# enabled = false
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
included-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Hide overlay filter' 'Hide player overlay filter'"
excluded-patches = "'Enable debug logging'"